BlogProj/Controllers/AnnonceController.cs
using BlogProj.DAO;
using BlogProj.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace BlogProj.Controllers
{
    [RoutePrefix("annonce")]
    [Route("{action=index}")]
    public class AnnonceController : Controller
    {
        // GET: Annonce
        [Route("")]
        public ActionResult Index(string sortOrder, int? page)
        {
            IAnnonceDAO annonceDAO = FabriqueDAO.GetAnnconceDAO();
            var annonces = annonceDAO.FindAll();
            
            ViewBag.TitreSortParam = String.IsNullOrEmpty(sortOrder) ? "titre_desc" : "";
            ViewBag.DateCreationSortParam = sortOrder == "datecreation" ? "datecreation_desc" : "datecreation";
            switch(sortOrder)
            {
                case "titre_desc":
                    annonces = annonces.OrderByDescending(a => a.Titre).ToList();
                    break;
                case "datecreation":
                    annonces = annonces.OrderBy(a => a.DateCreation).ToList();
                    break;
                case "datecreation_desc":
                    annonces = annonces.OrderByDescending(a => a.DateCreation).ToList();
                    break;
                default:
                    annonces = annonces.OrderBy(a => a.Titre).ToList();
                    break;
            }
            return View(annonces);
        }

        [Route("{id:long}")]
        public ActionResult Details(long id)
        {
            IAnnonceDAO annconceDAO = FabriqueDAO.GetAnnconceDAO();
            Annonce annonce = annconceDAO.FindById(id);
            return View(annonce);
        }

        [Route("add")]
        [Authorize]
        public ActionResult Create(object selectedAuteur = null)
        {
            IAuteurDAO auteurDao = FabriqueDAO.GetAuteurDAO();
            var auteurs = auteurDao.FindAll();
            //ViewBag.AuteurId = new SelectList(auteurs, "AuteurId", "Nom", selectedAuteur);
            ViewBag.AuteurId = new SelectList(auteurs, "AuteurId", "Nom", selectedAuteur);
            return View();
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        [Route("add")]
        public ActionResult Create([Bind(Include = "AnnonceId,Titre,Contenu,EstPublie,AuteurId")]Annonce annonce, string[] tags, IDictionary<string, int> competences)
        {
            annonce.DateCreation = DateTime.Now;
            annonce.MiseAJour = DateTime.Now;
            if (ModelState.IsValid)
            {
                IAnnonceDAO annonceDAO = FabriqueDAO.GetAnnconceDAO();
                annonce = AddTagToAnnonce(annonce, tags);
                annonce = AddCompetenceToAnnonce(annonce, competences);
                bool result = annonceDAO.Ajouter(annonce);
                return RedirectToAction("index");
            }
            else
            {
                return View(annonce);
            }
        }


        [Route("edit/{id}")]
        public ActionResult Edit(long? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Annonce annonce = FabriqueDAO.GetAnnconceDAO().FindById(id);
            PopulateAuteurDropDownList(annonce.AuteurId);
            return View(annonce);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("edit/{id}")]
        public ActionResult Edit([Bind(Include = "AnnonceId,Titre,Contenu,EstPublie,DateCreation,AuteurId")]Annonce annonce, string[] tags)
        {
            annonce.MiseAJour = DateTime.Now;
            //try
            //{
                if (ModelState.IsValid)
                {
                    IAnnonceDAO annonceDAO = FabriqueDAO.GetAnnconceDAO();
                    annonce = AddTagToAnnonce(annonce, tags);
                    bool result = annonceDAO.Edit(annonce);
                    return RedirectToAction("index");
                }
                else
                {
                    return View(annonce);
                }
            //}
            //catch (Exception)
            //{

            //    return RedirectToAction("index");
            //}
        }

        private void PopulateAuteurDropDownList(object selectedAuteur = null)
        {
            IAuteurDAO auteurDao = FabriqueDAO.GetAuteurDAO();
            var auteurs = auteurDao.FindAll();
            ViewBag.AuteurId = new SelectList(auteurs, "AuteurId", "Nom", selectedAuteur);
        }
        private Annonce AddTagToAnnonce(Annonce annonce, string[] tags)
        {
            if (tags != null)
            {
                List<Tag> tagList = new List<Tag>();
                foreach (string tag in tags)
                {
                    tagList.Add(new Tag(tag));
                }
                annonce.Tags = tagList; 
            }
            return annonce;
        }
        private Annonce AddCompetenceToAnnonce(Annonce annonce, IDictionary<string, int> competences)
        {
            ICompetenceDAO competenceDAO = FabriqueDAO.GetComptenceDAO();
            foreach(var key in competences.Keys)
            {
                var competence = competenceDAO.FindOneByDenomination(key);
                AnnonceCompetence annonceCompetence = new AnnonceCompetence();
                annonceCompetence.Competence = competence;
                annonceCompetence.Annonce = annonce;
                annonceCompetence.Niveau = competences[key];
                annonce.AnnonceCompetences.Add(annonceCompetence);
            }
            return annonce;
        }
        [Route("addCompetence")]
        public ActionResult FormAnnonceCompetenceView()
        {
            if (Request.IsAjaxRequest())
            {
                ICompetenceDAO competenceDAO = FabriqueDAO.GetComptenceDAO();
                ViewBag.competenceId = competenceDAO.FindAll();
                
                return PartialView("~/Views/AnnonceCompetence/CreatePartialAnnonceCompetence.cshtml");
                
            }
            return PartialView("Error");
            

        }

    }
}

BlogProj/Controllers/AuteurController.cs
using BlogProj.DAO;
using BlogProj.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BlogProj.Controllers
{
    [RoutePrefix("auteur")]
    [Route("{action=index}")]
    public class AuteurController : Controller
    {
        // GET: Auteur
        [Route("")]
        public ActionResult Index()
        {
            IAuteurDAO auteurDAO = FabriqueDAO.GetAuteurDAO();
            ICollection<Auteur> auteurs = auteurDAO.FindAll();
            return View(auteurs);
        }

        [Route("{id:long}")]
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IAuteurDAO auteurDAO = FabriqueDAO.GetAuteurDAO();
            Auteur auteur = auteurDAO.FindOne(id);
            if(auteur == null)
            {
                return HttpNotFound();
            }
            return View(auteur);
        }
        [Route("{id:long}/annonces")]
        public ActionResult Annonces(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IAnnonceDAO annonceDAO = FabriqueDAO.GetAnnconceDAO();
            var annonces = annonceDAO.FindByAuteurId(id);
           
            return View(annonces);
        }

        [Route("add")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("add")]
        public ActionResult Create([Bind(Include = "AuteurId,Prenom,Nom")]Auteur auteur)
        {
            if (ModelState.IsValid)
            {
                IAuteurDAO auteurDAO = FabriqueDAO.GetAuteurDAO();
                bool result = auteurDAO.Ajouter(auteur);
                return RedirectToAction("index");
            }
            else
            {
                return View(auteur);
            }
        }
    }
}

BlogProj/Controllers/CompetenceController.cs
using BlogProj.DAO;
using BlogProj.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogProj.Controllers
{
    [RoutePrefix("competence")]
    [Route("{action=index}")]
    public class CompetenceController : Controller
    {
        // GET: Competence
        [Route("")]
        public ActionResult Index()
        {
            ICompetenceDAO competenceDAO = FabriqueDAO.GetComptenceDAO();
            ICollection<Competence> competences = competenceDAO.FindAll();
            return View(competences);
        }

        [Route("add")]
        public ActionResult Create()
        {
            return View();
        }

        [Route("add")]
        [HttpPost]
        public ActionResult Create([Bind(Include = "CompetenceId,Denomination")]Competence competence)
        {
            if (ModelState.IsValid)
            {
                ICompetenceDAO competenceDAO = FabriqueDAO.GetComptenceDAO();
                competenceDAO.Add(competence);
                return RedirectToAction("index");
            }
            else
            {
                return View(competence);
            }
            
        }
    }
}

BlogProj/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SuperAnnonce.com", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">General <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                            <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Annonces", "Index", "Annonce")</li>
                    <li>@Html.ActionLink("Auteurs", "Index", "Auteur")</li>
                    <li>@Html.ActionLink("Competences", "Index", "Competence")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
   
</body>
</html>